apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ci-kind-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: rafter-rafter-upload-service
              servicePort: 80
            path: /v1/upload
          - backend:
              serviceName: rafter-minio
              servicePort: 9000
            path: /