---
# Source: rafter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-rafter
  namespace: default
  labels:
    app.kubernetes.io/name: rafter
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: rafter-1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rafter
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/managed-by: Tiller
      helm.sh/chart: rafter-1.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rafter
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Tiller
        helm.sh/chart: rafter-1.0.0
      annotations:
        
        dupa: 1
        recreate: '1572466665'
        sidecar.istio.io/inject: "false"
        
    spec:
      serviceAccountName: release-name-rafter
      containers:
        - name: rafter
          image: "eu.gcr.io/kyma-project/rafter:v1.0.0"
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            
            - --metrics-addr
            - :8080
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          env:
            # ClusterAssetsGroup
            
            - name: APP_CLUSTER_ASSET_GROUP_RELIST_INTERVALL
              value: 5m
              
            # AssetsGroup
            
            - name: APP_ASSET_GROUP_RELIST_INTERVALL
              value: 5m
              
            # ClusterBuckets
            
            - name: APP_CLUSTER_BUCKET_RELIST_INTERVAL
              value: 30s
              
            
            - name: APP_CLUSTER_BUCKET_MAX_CONCURRENT_RECONCILES
              value: 1
              
            
            - name: APP_CLUSTER_BUCKET_REGION
              value: us-east-1
              
            # Buckets
            
            - name: APP_BUCKET_RELIST_INTERVAL
              value: 30s
              
            
            - name: APP_BUCKET_MAX_CONCURRENT_RECONCILES
              value: 1
              
            
            - name: APP_BUCKET_REGION
              value: us-east-1
              
            # ClusterAssets
            
            - name: APP_CLUSTER_ASSET_RELIST_INTERVAL
              value: 30s
              
            
            - name: APP_CLUSTER_ASSET_MAX_CONCURRENT_RECONCILES
              value: 1
              
            # Assets
            
            - name: APP_ASSET_RELIST_INTERVAL
              value: 30s
              
            
            - name: APP_ASSET_MAX_CONCURRENT_RECONCILES
              value: 1
              
            # Store
            
            - name: APP_STORE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: APP_UPLOAD_ENDPOINT_WITH_PORT
                  name: assetstore-minio-docs-upload
              
            
            - name: APP_STORE_EXTERNAL_ENDPOINT
              value: dupa
              
            
            - name: APP_STORE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: accesskey
                  name: assetstore-minio
              
            
            - name: APP_STORE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secretkey
                  name: assetstore-minio
              
            
            - name: APP_STORE_USE_SSL
              valueFrom:
                configMapKeyRef:
                  key: APP_UPLOAD_SECURE
                  name: assetstore-minio-docs-upload
              
            
            - name: APP_STORE_UPLOAD_WORKERS_COUNT
              value: 10
              
            # Loader
            
            - name: APP_LOADER_VERIFY_SSL
              value: true
              
            
            - name: APP_LOADER_TEMPORARY_DIRECTORY
              value: /tmp
              
            # Webhooks
            
            - name: APP_WEBHOOK_VALIDATION_TIMEOUT
              value: 1m
              
            
            - name: APP_WEBHOOK_VALIDATION_WORKERS_COUNT
              value: 10
              
            
            - name: APP_WEBHOOK_MUTATION_TIMEOUT
              value: 1m
              
            
            - name: APP_WEBHOOK_MUTATION_WORKERS_COUNT
              value: 10
              
            
            - name: APP_WEBHOOK_METADATA_EXTRACTION_TIMEOUT
              value: 1m
              
            - name: APP_WEBHOOK_CFG_MAP_NAME
              value: release-name-rafter
            - name: APP_WEBHOOK_CFG_MAP_NAMESPACE
              value: default
