---
# Source: rafter/templates/service-account.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-rafter
  namespace: default
  labels:
    app.kubernetes.io/name: rafter
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: rafter-1.0.0
