---
# Source: rafter/templates/service-monitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: 
    release-name-rafter
  labels:
    prometheus: monitoring
    app.kubernetes.io/name: rafter
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: rafter-1.0.0
spec:
  endpoints:
    - interval: "30s"
      port: metrics
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: rafter
      app.kubernetes.io/instance: release-name
