image:
  repository: eu.gcr.io/kyma-project/rafter-upload-service
  tag: v1.0.0
  pullPolicy: IfNotPresent

deployment:
  labels: {}
  annotations: {}
  replicas: 1
  extraProperties: {}

pod:
  labels: {}
  annotations: {}
    # sidecar.istio.io/inject: "false"
    # recreate: {{ .Release.Time.Seconds | quote }}
  extraProperties: {}
    # strategy:
    #   type: RollingUpdate
    #   rollingUpdate:
    #     maxUnavailable: 0
  extraContainerProperties: {}

service:
  name:
  type: ClusterIP
  verbose: true
  host: "0.0.0.0"
  port:
    name: http
    internal: 3000
    external: 80
    protocol: TCP
  labels: {}
  annotations: {}
    # auth.istio.io/80: NONE

serviceAccount:
  create: true
  name:
  labels: {}
  annotations: {}

rbac:
  clusterScope:
    create: true
    role:
      name:
      labels: {}
      annotations: {}
      extraRules: []
    roleBinding:
      name:
      labels: {}
      annotations: {}

serviceMonitor:
  create: false
  name:
  scrapeInterval: 30s
  labels: {}
  annotations: {}