dependencies:
- name: rafter-controller-manager
  version: 0.1.*
  repository: "127.0.0.1:8879"
  condition: rafter-controller-manager.enabled
- name: rafter-upload-service
  version: 0.1.*
  repository: "127.0.0.1:8879"
  condition: rafter-upload-service.enabled
- name: rafter-front-matter-service
  version: 0.1.*
  repository: "127.0.0.1:8879"
  condition: rafter-front-matter-service.enabled
- name: rafter-asyncapi-service
  version: 0.1.*
  repository: "127.0.0.1:8879"
  condition: rafter-asyncapi-service.enabled