
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - cms.kyma-project.io
  resources:
  - assetgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cms.kyma-project.io
  resources:
  - assetgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cms.kyma-project.io
  resources:
  - clusterassetgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cms.kyma-project.io
  resources:
  - clusterassetgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
- apiGroups:
  - rafter.kyma-project.io
  resources:
  - assets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rafter.kyma-project.io
  resources:
  - assets/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - rafter.kyma-project.io
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rafter.kyma-project.io
  resources:
  - buckets/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - rafter.kyma-project.io
  resources:
  - clusterassets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rafter.kyma-project.io
  resources:
  - clusterassets/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - rafter.kyma-project.io
  resources:
  - clusterbuckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rafter.kyma-project.io
  resources:
  - clusterbuckets/status
  verbs:
  - get
  - list
  - patch
  - update
