apiVersion: v1
entries:
  rafter:
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2019-11-18T13:42:12.181289+01:00"
    description: A umbrella Helm chart for Rafter Controller Manager and Rafter services
    digest: e8c8116b90be1129d9fb0cb257a105a9962d261fcd316df0522dc7feee99f1c8
    home: https://github.com/kyma-project/rafter
    keywords:
    - rafter
    - storage
    - assets
    - buckets
    - assetgroups
    - controller-manager
    - webhook
    - upload
    - front-matter
    - asyncapi
    - minio
    maintainers:
    - email: lukasz.gornicki.83@gmail.com
      name: derberg
    - email: michal@hudy.pl
      name: michal-hudy
    - email: marcin.witalis@gmail.com
      name: m00g3n
    - email: mati6095@gmail.com
      name: aerfio
    - email: filip.strozik@outlook.com
      name: pPrecel
    - email: urbanczyk.maciej.95@gmail.com
      name: magicmatatjahu
    name: rafter
    sources:
    - https://github.com/kyma-project/rafter
    urls:
    - rafter-0.1.0.tgz
    version: 0.1.0
  rafter-asyncapi-service:
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2019-11-18T13:42:12.182404+01:00"
    description: A Helm chart for AsyncAPI Service
    digest: 03708f1ed032e97e232ff84955aaae2744b48c744beea6b905c54ecc3e8deeb3
    home: https://github.com/kyma-project/rafter
    keywords:
    - rafter
    - storage
    - assets
    - buckets
    - assetgroups
    - asyncapi
    - webhook
    - minio
    maintainers:
    - email: lukasz.gornicki.83@gmail.com
      name: derberg
    - email: michal@hudy.pl
      name: michal-hudy
    - email: marcin.witalis@gmail.com
      name: m00g3n
    - email: mati6095@gmail.com
      name: aerfio
    - email: filip.strozik@outlook.com
      name: pPrecel
    - email: urbanczyk.maciej.95@gmail.com
      name: magicmatatjahu
    name: rafter-asyncapi-service
    sources:
    - https://github.com/kyma-project/rafter
    urls:
    - rafter-asyncapi-service-0.1.0.tgz
    version: 0.1.0
  rafter-controller-manager:
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2019-11-18T13:42:12.185066+01:00"
    description: A Helm chart for Rafter Controller Manager
    digest: 115ab3d243257a4fdfef05fc1615ee4ed46ede4ea4fb6da8fc81e0e36521c754
    home: https://github.com/kyma-project/rafter
    keywords:
    - rafter
    - storage
    - assets
    - buckets
    - assetgroups
    - controller-manager
    - minio
    maintainers:
    - email: lukasz.gornicki.83@gmail.com
      name: derberg
    - email: michal@hudy.pl
      name: michal-hudy
    - email: marcin.witalis@gmail.com
      name: m00g3n
    - email: mati6095@gmail.com
      name: aerfio
    - email: filip.strozik@outlook.com
      name: pPrecel
    - email: urbanczyk.maciej.95@gmail.com
      name: magicmatatjahu
    name: rafter-controller-manager
    sources:
    - https://github.com/kyma-project/rafter
    urls:
    - rafter-controller-manager-0.1.0.tgz
    version: 0.1.0
  rafter-front-matter-service:
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2019-11-18T13:42:12.186073+01:00"
    description: A Helm chart for Front Matter Service
    digest: dc8f53dcf6ed6dab18ec2bf46977db79631016e9aeb6852b32d14cedecc087e1
    home: https://github.com/kyma-project/rafter
    keywords:
    - rafter
    - storage
    - assets
    - buckets
    - assetgroups
    - front-matter
    - webhook
    - minio
    maintainers:
    - email: lukasz.gornicki.83@gmail.com
      name: derberg
    - email: michal@hudy.pl
      name: michal-hudy
    - email: marcin.witalis@gmail.com
      name: m00g3n
    - email: mati6095@gmail.com
      name: aerfio
    - email: filip.strozik@outlook.com
      name: pPrecel
    - email: urbanczyk.maciej.95@gmail.com
      name: magicmatatjahu
    name: rafter-front-matter-service
    sources:
    - https://github.com/kyma-project/rafter
    urls:
    - rafter-front-matter-service-0.1.0.tgz
    version: 0.1.0
  rafter-upload-service:
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2019-11-18T13:42:12.188583+01:00"
    description: A Helm chart for Upload Service
    digest: d6f0bb11967f6833f16503734052336fa176ebc25531748e4b1631a2a4ea9c75
    home: https://github.com/kyma-project/rafter
    keywords:
    - rafter
    - storage
    - assets
    - buckets
    - assetgroups
    - upload
    - webhook
    - minio
    maintainers:
    - email: lukasz.gornicki.83@gmail.com
      name: derberg
    - email: michal@hudy.pl
      name: michal-hudy
    - email: marcin.witalis@gmail.com
      name: m00g3n
    - email: mati6095@gmail.com
      name: aerfio
    - email: filip.strozik@outlook.com
      name: pPrecel
    - email: urbanczyk.maciej.95@gmail.com
      name: magicmatatjahu
    name: rafter-upload-service
    sources:
    - https://github.com/kyma-project/rafter
    urls:
    - rafter-upload-service-0.1.0.tgz
    version: 0.1.0
generated: "2019-11-18T13:42:12.175494+01:00"
