image:
  repository: eu.gcr.io/kyma-project/rafter-metadata-service
  tag: v1.0.0
  pullPolicy: IfNotPresent

deployment:
  labels: {}
  annotations: {}
  replicas: 1
  extraProperties: {}

pod:
  labels: {}
  annotations: {}
    # sidecar.istio.io/inject: "false"
  extraProperties: {}
    # strategy:
    #   type: RollingUpdate
    #   rollingUpdate:
    #     maxUnavailable: 0
  extraContainerProperties: {}

service:
  name:
  type: ClusterIP
  verbose: true
  host: "0.0.0.0"
  port:
    name: http
    internal: 3000
    external: 80
    protocol: TCP
  labels: {}
  annotations: {}
    # auth.istio.io/80: NONE    

serviceMonitor:
  create: false
  name:
  scrapeInterval: 30s
  labels: {}
  annotations: {}