# Default values for rafter-front-matter-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride:
fullnameOverride:

image:
  repository: rafter-front-matter-service
  tag: latest
  pullPolicy: Never

deployment:
  labels: {}
  annotations: {}
  replicas: 1
  extraProperties: {}

pod:
  labels: {}
  annotations: {}
    # sidecar.istio.io/inject: "false"
  extraProperties: {}
    # strategy:
    #   type: RollingUpdate
    #   rollingUpdate:
    #     maxUnavailable: 0
  extraContainerProperties: {}

service:
  name:
  type: ClusterIP
  port:
    name: http
    internal: 3000
    external: 80
    protocol: TCP
  labels: {}
  annotations: {}
    # auth.istio.io/80: NONE    

serviceMonitor:
  create: false
  name:
  scrapeInterval: 30s
  labels: {}
  annotations: {}

envs:
  host:
    value: "0.0.0.0"
  verbose: 
    value: "true"
  timeout:
    value: "1m"
  workers:
    value: "10"