{{- if .Values.rbac.clusterScope.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "rafterUploadService.rbacClusterRoleName" . }}
  labels:
    app.kubernetes.io/name: {{ include "rafterUploadService.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "rafterUploadService.chart" . }}
  {{- if .Values.rbac.clusterScope.role.labels }}
    {{ toYaml .Values.rbac.clusterScope.role.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.rbac.clusterScope.role.annotations }}
  annotations:
    {{ toYaml .Values.rbac.clusterScope.role.annotations | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create"]
{{- if .Values.rbac.clusterScope.role.extraRules }}
{{ toYaml .Values.rbac.clusterScope.role.extraRules | nindent 0 }}
{{- end }}
{{- end }}
