{{- if .Values.serviceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rafterUploadService.serviceMonitorName" . }}
  labels:
    prometheus: monitoring
    app.kubernetes.io/name: {{ include "rafterUploadService.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: rafter
    helm.sh/chart: {{ include "rafterUploadService.chart" . }}
  {{- if .Values.serviceMonitor.labels }}
    {{ include "rafter.rafterUploadService" ( dict "value" .Values.serviceMonitor.labels "context" . ) | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceMonitor.annotations }}
  annotations:
    {{ include "rafter.rafterUploadService" ( dict "value" .Values.serviceMonitor.annotations "context" . ) | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.scrapeInterval }}
      port: {{ .Values.service.port.name }}
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rafterUploadService.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
