{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rafterUploadService.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "rafterUploadService.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: rafter
    helm.sh/chart: {{ include "rafterUploadService.chart" . }}
  {{- if .Values.serviceAccount.labels }}
    {{ include "rafter.rafterUploadService" ( dict "value" .Values.serviceAccount.labels "context" . ) | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{ include "rafter.rafterUploadService" ( dict "value" .Values.serviceAccount.annotations "context" . ) | nindent 4 }}
  {{- end }}
{{- end }}
