apiVersion: v1
kind: Service
metadata:
  name: {{ include "rafterUploadService.serviceName" . }}
  labels:
    app.kubernetes.io/name: {{ include "rafterUploadService.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "rafterUploadService.chart" . }}
  {{- if .Values.service.labels }}
    {{ toYaml .Values.service.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.port.name }}
      port: {{ .Values.service.port.external }}
      protocol: {{ .Values.service.port.protocol }}
      targetPort: {{ .Values.service.port.internal }}
  selector:
    app.kubernetes.io/name: {{ include "rafterUploadService.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
