---
# Source: rafter-metadata-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-rafter-metadata-service
  labels:
    app.kubernetes.io/name: rafter-metadata-service
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: rafter-metadata-service-1.0.0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rafter-metadata-service
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Tiller
        helm.sh/chart: rafter-metadata-service-1.0.0
    spec:
      containers:
        - name: rafter-metadata-service
          image: "eu.gcr.io/kyma-project/rafter-metadata-service:v1.0.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_PORT
              value: 3000
            - name: APP_HOST
              value: "0.0.0.0"
            
            - name: APP_PROCESS_TIMEOUT
              value: 1m
              
            
            - name: APP_MAX_WORKERS
              value: 10
              
            - name: APP_VERBOSE
              value: true
