---
# Source: rafter-metadata-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-rafter-metadata-service
  labels:
    app.kubernetes.io/name: rafter-metadata-service
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: rafter-metadata-service-1.0.0
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: rafter-metadata-service
    app.kubernetes.io/instance: release-name
