apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rafter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "rafter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "rafter.chart" . }}
  {{- if .Values.deployment.labels }}
    {{ toYaml .Values.deployment.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.deployment.annotations }}
  annotations:
    {{ toYaml .Values.deployment.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  {{- if .Values.deployment.extraProperties }}
  {{ toYaml .Values.deployment.extraProperties | nindent 2 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rafter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      helm.sh/chart: {{ include "rafter.chart" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rafter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "rafter.chart" . }}
      {{- if .Values.pod.labels }}
        {{ toYaml .Values.pod.labels | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.pod.labels }}
        {{ toYaml .Values.metrics.pod.labels | nindent 8 }}
      {{- end }}
      {{- if or .Values.pod.annotations (and .Values.metrics.enabled .Values.metrics.pod.annotations) }}
      annotations:
      {{- if .Values.pod.annotations }}
        {{ toYaml .Values.pod.annotations | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.enabled }}
        {{ toYaml .Values.metrics.pod.annotations | nindent 8 }}
      {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "rafter.serviceAccountName" . }}
      {{- if .Values.pod.volumes }}
      volumes:
        {{ toYaml .Values.pod.volumes | nindent 8 }}
      {{- end }}
      {{- if .Values.pod.extraProperties }}
      {{ toYaml .Values.pod.extraProperties | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ include "rafter.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- $replicas := int (toString (.Values.deployment.replicas)) -}}
          {{- if or .Values.metrics.enabled (gt $replicas 1) }}
          command:
            - /manager
          args:
            {{ if gt $replicas 1 }}
            - --enable-leader-election
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - --metrics-addr
            - :{{ .Values.metrics.service.port.external }}
            {{- end }}
          {{- end }}
          {{- if .Values.metrics.enabled }}
          ports:
            - name: {{ .Values.metrics.service.port.name }}
              containerPort: {{ .Values.metrics.service.port.external }}
              protocol: {{ .Values.metrics.service.port.protocol }}
          {{- end }}
          {{- if .Values.pod.resources }}
          resources:
            {{ toYaml .Values.pod.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.pod.volumeMounts }}
          volumeMounts:
            {{ toYaml .Values.pod.volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .Values.pod.extraContainerProperties }}
          {{ toYaml .Values.pod.extraContainerProperties | nindent 10 }}
          {{- end }}
          env:
            # ClusterAssetsGroup
            - name: APP_CLUSTER_ASSET_GROUP_RELIST_INTERVALL
              {{ toYaml .Values.envs.clusterAssetGroup.relistInterval | nindent 14 }}
            # AssetsGroup
            - name: APP_ASSET_GROUP_RELIST_INTERVALL
              {{ toYaml .Values.envs.assetGroup.relistInterval | nindent 14 }}
            # ClusterBuckets
            - name: APP_CLUSTER_BUCKET_RELIST_INTERVAL
              {{ toYaml .Values.envs.clusterBucket.relistInterval | nindent 14 }}
            - name: APP_CLUSTER_BUCKET_MAX_CONCURRENT_RECONCILES
              {{ toYaml .Values.envs.clusterBucket.maxConcurrentReconciles | nindent 14 }}
            - name: APP_CLUSTER_BUCKET_REGION
              {{ toYaml .Values.envs.clusterBucket.region | nindent 14 }}
            # Buckets
            - name: APP_BUCKET_RELIST_INTERVAL
              {{ toYaml .Values.envs.bucket.relistInterval | nindent 14 }}
            - name: APP_BUCKET_MAX_CONCURRENT_RECONCILES
              {{ toYaml .Values.envs.bucket.maxConcurrentReconciles | nindent 14 }}
            - name: APP_BUCKET_REGION
              {{ toYaml .Values.envs.bucket.region | nindent 14 }}
            # ClusterAssets
            - name: APP_CLUSTER_ASSET_RELIST_INTERVAL
              {{ toYaml .Values.envs.clusterAsset.relistInterval | nindent 14 }}
            - name: APP_CLUSTER_ASSET_MAX_CONCURRENT_RECONCILES
              {{ toYaml .Values.envs.clusterAsset.maxConcurrentReconciles | nindent 14 }}
            # Assets
            - name: APP_ASSET_RELIST_INTERVAL
              {{ toYaml .Values.envs.asset.relistInterval | nindent 14 }}
            - name: APP_ASSET_MAX_CONCURRENT_RECONCILES
              {{ toYaml .Values.envs.asset.maxConcurrentReconciles | nindent 14 }}
            # Store
            - name: APP_STORE_ENDPOINT
              {{ toYaml .Values.envs.store.endpoint | nindent 14 }}
            - name: APP_STORE_EXTERNAL_ENDPOINT
              {{ toYaml .Values.envs.store.externalEndpoint | nindent 14 }}
            - name: APP_STORE_ACCESS_KEY
              {{ toYaml .Values.envs.store.accessKey | nindent 14 }}
            - name: APP_STORE_SECRET_KEY
              {{ toYaml .Values.envs.store.secretKey | nindent 14 }}
            - name: APP_STORE_USE_SSL
              {{ toYaml .Values.envs.store.useSSL | nindent 14 }}
            - name: APP_STORE_UPLOAD_WORKERS_COUNT
              {{ toYaml .Values.envs.store.uploadWorkers | nindent 14 }}
            # Loader
            - name: APP_LOADER_VERIFY_SSL
              {{ toYaml .Values.envs.loader.verifySSL | nindent 14 }}
            - name: APP_LOADER_TEMPORARY_DIRECTORY
              {{ toYaml .Values.envs.loader.tempDir | nindent 14 }}
            # Webhooks
            - name: APP_WEBHOOK_VALIDATION_TIMEOUT
              {{ toYaml .Values.envs.webhooks.validation.timeout | nindent 14 }}
            - name: APP_WEBHOOK_VALIDATION_WORKERS_COUNT
              {{ toYaml .Values.envs.webhooks.validation.workers | nindent 14 }}
            - name: APP_WEBHOOK_MUTATION_TIMEOUT
              {{ toYaml .Values.envs.webhooks.mutation.timeout | nindent 14 }}
            - name: APP_WEBHOOK_MUTATION_WORKERS_COUNT
              {{ toYaml .Values.envs.webhooks.mutation.workers | nindent 14 }}
            - name: APP_WEBHOOK_METADATA_EXTRACTION_TIMEOUT
              {{ toYaml .Values.envs.webhooks.metadata.timeout | nindent 14 }}
            - name: APP_WEBHOOK_CFG_MAP_NAME
              value: {{ include "rafter.webhooksConfigMapName" . }}
            - name: APP_WEBHOOK_CFG_MAP_NAMESPACE
              value: {{ .Release.Namespace }}
